name: Test Build

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Install and Build 🔧
        run: |
          npm ci --include=dev
          sed 's/<your MapTiler key>/53iZvB2drcamS0Ge0xiD/g' src/configs/config.maptiler.js > src/config.js
          npm run build
        # MapTiler key 53iZvB2drcamS0Ge0xiD only allows requests from zelonewolf.github.io
